swagger: "2.0"
info:
  version: "0.0.1"
  title: Moneybags
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  
paths:
  x-swagger-router-controller: plaidController
  /get_access_token:
    post:
      description: Get the access token for a bank item with the appropriate access tokens and item_id from either Plaid LINK or app database
      operationId: getAccessToken
      parameters: 
      - name: public_token
        in: body
        description: The public access token provided by LINK, local storage, or the app's database
        schema: 
          $ref: '#/definitions/Plaid'
      responses:
        '200':
          description: Token obtained
          schema:
            $ref: '#/definitions/Plaid'
          
definitions:
  Plaid:
    type: object
    properties:
      access_token:
        type: string
        description: Unique identifier representing the secret for the linked item.
      item_id:
        type: string
        description: Another identifier for the linked item.
