version: 2
jobs:
    # The build job
    build:
        working_directory: ~/project3
        docker:
            - image: circleci/node:6.10-browsers
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init --recursive || (rm -fr .git/config .git/modules && git submodule deinit -f . && git submodule update --init --recursive)
            - run: git submodule foreach git pull origin develop
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            - run:
                name: Install local dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # Test the source code
            - run:
                name: Testing
                command: npm run test
            # Build project with different configuration based on
            # the current branch
            #- run:
            #    name: Building
            #    command: |
            #        if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            #            npm run build-dev
            #        elif [ "${CIRCLE_BRANCH}" == "uat" ]; then
            #            npm run build-qa
            #        else
            #            npm run build-prod
            #        fi
            # Cache the dist folder for the deploy job
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist